---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: backup-secret
spec:
  # Vault CSI Provider
  provider: vault
  secretObjects:
  - secretName: backup-secret
    type: Opaque
    data: 
    - objectName: access_key
      key: access_key
    - objectName: secret_key
      key: secret_key
  parameters:
    # Vault role name to use during login
    roleName: "kubernetes"
    # Vault's hostname
    vaultAddress: "https://vault.default:8200"
    # TLS CA certification for validation
    objects: |
      - objectName: "access_key"
        secretPath: "secret/data/backup-secret"
        secretKey: "access_key"
      - objectName: "secret_key"
        secretPath: "secret/data/backup-secret"
        secretKey: "secret_key"
    # "objectName" is an alias used within the SecretProviderClass to reference 
    # that specific secret. This will also be the filename containing the secret.
    # "secretPath" is the path in Vault where the secret should be retrieved.
    # "secretKey" is the key within the Vault secret response to extract a value from.
