apiVersion: batch/v1
kind: Job
metadata:
  name: restore-${SITE_NAME_HYPHEN}
  annotations:
    vault.banzaicloud.io/vault-addr: "https://vault.default:8200"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-business-business
      serviceAccountName: ${SITE_NAME_HYPHEN}
      securityContext: {}
      volumes:
        - name: config-volume
          configMap:
            name: ${SITE_NAME_HYPHEN}-configmap
        - name: wp-uploads-${SITE_NAME_HYPHEN}
          persistentVolumeClaim:
            claimName: wp-uploads-${SITE_NAME_HYPHEN}
        - emptyDir:
            medium: Memory
          name: vault-env
        - name: vault-tls
          secret:
            secretName: vault-tls
      containers:
        - name: ${SITE_NAME_HYPHEN}-restorebackup
          env:
            - name: DATABASE_HOST
              value: "${SITE_NAME_HYPHEN}-mysql.wordpress.svc"
            - name: DATABASE_USER
              valueFrom:
              secretKeyRef:
                name: ${SITE_NAME_HYPHEN}-db-creds-secret
                key: user
            - name: DATABASE_NAME
              valueFrom:
              secretKeyRef:
                name: ${SITE_NAME_HYPHEN}-db-creds-secret
                key: name
            - name: DATABASE_PASS
              valueFrom:
              secretKeyRef:
                name: ${SITE_NAME_HYPHEN}-db-creds-secret
                key: pass
            - name: BUCKET
              value: "hostkraken-backup"
            - name: AWS_ACCESS_KEY_ID
              value: "vault:secret/data/backup-secret#access_key"
            - name: AWS_SECRET_ACCESS_KEY
              value: "vault:secret/data/backup-secret#secret_key"
            - name: SITE_NAME
              value: ${SITE_NAME}
            - name: RESTOREPOINT
              value: ${RESTOREPOINT}
          volumeMounts:
          - name: config-volume
            mountPath: /configs
          - name: wp-uploads-${SITE_NAME_HYPHEN}
            mountPath: /content
          - mountPath: /vault/
            name: vault-env
          - mountPath: /vault/tls/ca.crt
            name: vault-tls
            subPath: ca.crt
          securityContext: {}
          image: "registry.digitalocean.com/business-business/restoresite:latest"
          imagePullPolicy: Always
          args:
          - /bin/restore-site ${SITE_NAME_HYPHEN}
